### ISSUE TITLE
Support npm completion

### ISSUE THREAD

**Issue by libinvarghese** [chanzo/script-launcher#103]
It would be great feature to have npm completion feature for `npm start` just as how we have for `npm run`

After migrating to launch, currently if I do `npm run <tab>`, my shell (zsh) just throws
```
start
```

Previously I used to get suggestions of all scripts under the `scripts` key in `package.json`. (Refer https://github.com/npm/cli/blob/4c65cd952bc8627811735bea76b9b110cc4fc80e/lib/run-script.js#L17)

**Comment by Heerschop** [comment]
Sounds like a valuable functionality to add, is there some more information on how to accomplish this? Isn't this a change on **zsh**? What is the link to npm about?

For now, you could use the [menu](https://www.npmjs.com/package/script-launcher#interactive-menu) functionality of script **script-launcher**  to easy your workflow.

### Example:
``` bash
➜  npm start

? Select action › - Use arrow-keys. Return to submit.
❯   serve - Serve your app.
    build
```

**Comment by libinvarghese** [comment]
The **menu** is the main reason I migrated to `script-launcher` 👍 🙏 👏 

You may be right! This should be a `zsh` plugin.

Since I am not familiar with the underlying architecture of `npm`, I did try to just look around the auto-complete feature I realised -— `npm` has a completion (auto-suggest/auto-complete) functionality built-in. For instance the auto completion of a `run-script` is implemented [here](https://github.com/npm/cli/blob/4c65cd952bc8627811735bea76b9b110cc4fc80e/lib/run-script.js#L17). Based on this code, I don't see how we can extend this functionality into the script that is being called.

I just tried [tabtab](https://github.com/mklabs/tabtab)<sup id="tabtab">[1](#tabtabAlt)</sup>. An excellent tool to accomplish this. Unfortunately we won't be able to do `npm start <tab>` but we could do `.node_modules/.bin/launch <tab>`. For `npx launch <tab>` to work, we would need to add npx auto-complete, which I believe is a npx issue<sup id="npx">[2](#npx-complete)</sup> altogether.

<b id="tabtabAlt">1</b> [omelette](https://github.com/f/omelette) Alternative to [tabtab](https://github.com/mklabs/tabtab) [↩](#tabtab)
<b id="npx-complete">2</b> [partial npx auto-complete solution](https://github.com/zkat/npx/issues/5) [↩](#npx)

**Comment by Heerschop** [comment]
To make `zsh` autocompletion possible for `script-launcher` there has to be a autocompletion scripts installed as explained in this article:

[Using scripts in any language for Bash/Zsh tab completion](https://saveriomiroddi.github.io/Using-scripts-in-any-language-for-bash-zsh-tab-completion/)

**Comment by Heerschop** [comment]
As of **script-launcher** version [1.26.0](https://github.com/chanzo/script-launcher/releases/tag/1.26.0) i have added the list command.

Now you can add sort of an [experimental tab completion support](https://github.com/chanzo/script-launcher#experimental-tab-completion-support-for-script-launcher-in-zsh), for **script-launcher** by executing the follow command in the current shell.
``` bash
complete -C "npx launch list" -o default 'npm'
# Or when script-launcher is installed globally
complete -C "launch list" -o default 'npm'
```
The solution in its current state is far from optimal, there are several problems with it, but it is a starting point.

**Comment by Heerschop** [comment]
When using **script-launcher** version [1.26.0](https://github.com/chanzo/script-launcher/releases/tag/1.26.0) or higher. You can paste in these commands, for some basic tab completion support:
``` bash
eval "$(npm completion)"

_launch_completion () {
  if [[ $COMP_LINE != "npm start"* ]] ; then
    _npm_completion
  else
    npx launch list
  fi
}
complete -o default -F _launch_completion npm
```

This function will test if you are using tab completion on `npm start` if so it will execute `npx launch list` if not it will execute the default npm completion function `_npm_completion`.

**Comment by Heerschop** [comment]
As of **script-launcher** version [1.26.1](https://github.com/chanzo/script-launcher/releases/tag/1.26.1) you can [enable tab completion](https://www.npmjs.com/package/script-launcher#enable-tab-completion)
