### ISSUE TITLE
Condition: Using values returned from shell command

### ISSUE THREAD

**Issue by tarwin** [chanzo/script-launcher#112]
Firstly, thanks for the amazing utility. Super helpful.

I've been trying to get the following pattern to work, to check if there is anything not commited to Git, and if so do not deploy.

It looks as follows, but never actually works (It always fails, and thus ends up deploying).

```
    "deploy": [
      {
        "condition": "'if [[ -z \"$(git status -s)\" ]]; then echo \"true\"; else echo \"false\"; fi'",
        "sequential-then": "echo '❌ Please commit all Git changes before deploying\n\n'",
        "sequential-else": [
                ... // do deploy
        ]
```

I can do it as follows but it that isn't working within your great conditional structure.

```
    "deploy": [
      "testGit",
      ... // deploy
    ],
    "testGit": "if [[ -z \"$(git status -s)\" ]]; then echo \"✅ Git Commited.\"; else echo \"❌ Please commit all Git changes before deploying.\n\n\"; exit 1; fi",
```

Am I missing something or is this not supported?

**Comment by Heerschop** [comment]
The git command `git status -s` will always return 0 even if there are changes to be committed. You can use `git diff --exit-code` this git command will return different exit codes depending on git changes being there or not.

If your rewrite your pattern as:
``` json
{
  "scripts": {
    "deploy": [
      {
        "condition": "git diff --exit-code",
        "sequential-then": "echo Executing deploy actions.",
        "sequential-else": "echo '❌ Please commit all Git changes before deploying...\n\n'"
      }
    ]
  }
}
```
Then it should work.

**Comment by Heerschop** [comment]
In you case the command is always returning an error non-zero value.

The commands that are executed by script-launcher will be executed in the default shell that is defined by the [shell option of spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options). 

On my machine the default shell for [child_process.spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) is `/bin/dash` the command you are executing `if [[ -z \"$(git status -s)\" ]]; then echo \"true\"; else echo \"false\"; fi` is not compatibal with this shell. You can check which shell is being used by executing `echo SHELL: $(readlink /proc/$$/exe)` on a linux/unix based system. 
#### Show shell example:
``` json
{
  "scripts": {
    "show-shell": [
      "echo SHELL: $(readlink /proc/$$/exe)"
    ]
  }
}
```

Use the [script-launcher options](https://www.npmjs.com/package/script-launcher#script-shell) to change the default shell being used.

**Be advised:** If possible don't change the default shell, this will probably break interoperability between different Operating Systems. So if this is important for you always try a different implementation, as I suggested en in previous comment.
