### ISSUE TITLE
Question about Concurrent scripts. 

### ISSUE THREAD

**Issue by tech-consortium** [chanzo/script-launcher#117]
@chanzo 
So I have an multi-application Angular project where I need to build two common library projects followed by several projects that depend on two common libraries.  I was expecting the following to build the sequential projects first, then all the rest concurrently. 

...
"build:all": {
      "sequential": [
        "build:process-classes",
        "build:common:js",
        "build:common:css",
      ],
        "concurrent": [
        "build:app1",
        "build:app2",
        "build:app3",
        "build:app4",
        "build:app5"
      ]
    },
...

Instead of waiting until all sequential projects complete before it launches the concurrent projects, it launches both sequential and concurrent at the same time.   What's the correct way to accomplish what I need?

**Comment by tech-consortium** [comment]
Also, how do we limit the maximum number of concurrent tasks it can start at one time?  For example, npm-run-all has a parameter --max-parallel.

**Comment by Heerschop** [comment]
You get the desired behavior by rewriting your setup to:
``` json
{
  "scripts": {
    "build:$action:$extention=": [
      "echo $action $extention",
      "sleep 1"
    ],
    "build:all": [
      "build:process-classes",
      "build:common:js",
      "build:common:css",
      {
        "concurrent": [
          "build:app1",
          "build:app2",
          "build:app3",
          "build:app4",
          "build:app5"
        ]
      }
    ]
  }
}
```
Or as an inline script block:
``` json
{
  "scripts": {
    "build:$action:$extention=": [
      "echo $action $extention",
      "sleep 1"
    ],
    "build:all": [
      "build:process-classes",
      "build:common:js",
      "build:common:css",
      [
        "build:app1",
        "build:app2",
        "build:app3",
        "build:app4",
        "build:app5"
      ]
    ]
  }
}
```
Currently there is no way to limit the number of concurrent tasks.I will create a parameter for this.

**Comment by Heerschop** [comment]
As of release [1.29.0](https://github.com/chanzo/script-launcher/releases/tag/1.29.0) you can limit the number of concurrent tasks.
