### ISSUE TITLE
Enable run concurrently with repeater

### ISSUE THREAD

**Issue by vuphan365** [chanzo/script-launcher#125]
First of all, thanks for your contribute, this project help us reduce a lot of time for building with concurrent mode.
However, if you can, please provide a option to run repeater concurrent/sequential. I see it is sequential at default now.

Thanks

**Comment by Heerschop** [comment]
You can make the [repeater example](https://www.npmjs.com/package/script-launcher#repeaters-string) concurrent by changing the "ping" block to `[[` .... `]]` see example below:
```json
{
  "scripts": {
    "ping": [[
      {
        "repeater": "$launch_setting_servers",
        "sequential": [
          "echo Action: $launch_setting_command $_ && sleep 2"
        ]
      }
    ]]
  },
  "settings": {
    "command": "ping",
    "servers": [
      "www.google.com",
      "duckduckgo.com",
      "bing.com"
    ]
  }
}
```
