### ISSUE TITLE
Add functionality to run script names with glob patterns

### ISSUE THREAD

**Issue by libinvarghese** [chanzo/script-launcher#99]
It would great to have an equivalent of `npm-run-all build:*` which could run `npm run build:css && npm run build:js && npm run build:html` where you could pass the script name as a glob pattern.

Could you also support both sequential & concurrent?

**Suggestion**
```
{
  "scripts": {
    "build:css": "...",
    "build:js": "...",
    "build:html": "...",
    "build:all": {
      "sequential": [ "build:*" ],
      "concurrent": [ "build:*" ],
    },
}
```

**Comment by Heerschop** [comment]
Added support for using wildcard characters when referring to script in version [1.25.0](https://github.com/chanzo/script-launcher/releases/tag/1.25.0)

**Comment by Heerschop** [comment]
Added support for using wildcard characters when referring to script in version [1.25.0](https://github.com/chanzo/script-launcher/releases/tag/1.25.0)
